[package]
name = "tf-fluids"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tf-core = { path = "../tf-core" }
thiserror.workspace = true
rfluids = "0.3"
uom.workspace = true

[dev-dependencies]
proptest = "1.0"