[package]
name = "tf-project"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tf-core = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
